

var datosUsuarios=[

{
nombre: "Mariano",
apellidos:"suarez",
dni:13956541,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},
    
{
nombre: "Mariano",
apellidos:"suarez",
dni:14956541,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13956544,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:139565333,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13956550,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13956001,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13957801,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:18956541,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13969841,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13997841,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:139900541,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:1395881,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13956541,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13958941,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13959901,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13953471,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13798941,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},    
{
nombre: "Mariano",
apellidos:"suarez",
dni:13349641,
mail: "marianosuarez@gmail.com",
contraseña:"perrito23",
seguidores:400,
seguidos: 600,
cantidadDePublicaciones: 30,
post: [],
},


]

module.exports=datosUsuarios;