var datosUsuarios = [
{
nombre: "Mariano",
apellido: "Suarez",
nombreDeUsuario: "marianosuarez",
fotoDePerfil: [],
dni: 13956541,
mail: "marianosuarez@gmail.com",
contraseña: "perrito23",
seguidores: 400,
seguidos: 600,
cantidadDePublicaciones: 30,
posts: [],
},
    
{
nombre: "Virginia",
apellido: "López",
nombreDeUsuario: "vlopez1",
fotoDePerfil: [],
dni:14956541,
mail: "virginialopez@gmail.com",
contraseña:"estrellita10",
seguidores: 1058,
seguidos: 563,
cantidadDePublicaciones: 10,
posts: [],
},    
{
nombre: "Lucia",
apellido: "Marquez",
nombreDeUsuario: "luciaaa_m",
fotoDePerfil: [],
dni: 13956544,
mail: "luciamarquez@gmail.com",
contraseña: "dulcedeleche",
seguidores: 600,
seguidos: 580,
cantidadDePublicaciones: 20,
posts: [],
},    
{
nombre: "Camila",
apellido: "García Mansilla",
nombreDeUsuario: "camigm45",
fotoDePerfil: [],
dni: 13956533,
mail: "camilagmansilla@gmail.com",
contraseña: "cocacolalight",
seguidores: 4500,
seguidos: 600,
cantidadDePublicaciones: 30,
posts: [],
},    
{
nombre: "Trinidad",
apellido: "Diaz Colodrero",
nombreDeUsuario: "marianosuarez",
fotoDePerfil: [],
dni: 13956550,
mail: "trinidc@gmail.com",
contraseña: "trinidad123",
seguidores: 400,
seguidos: 600,
cantidadDePublicaciones: 27,
posts: [],
},    
{
nombre: "María",
apellido: "García Zavaleta",
nombreDeUsuario: "mgzavaleta",
fotoDePerfil: [],
dni: 13956001,
mail: "mgarciazavaleta@gmail.com",
contraseña: "arcoiris2020",
seguidores: 457,
seguidos: 700,
cantidadDePublicaciones: 44,
posts: [],
},    
{
nombre: "Nicolás",
apellido: "Zavaleta",
nombreDeUsuario: "nicozava2",
fotoDePerfil: [],
dni: 13957801,
mail: "nicozavaleta@gmail.com",
contraseña: "gatito10",
seguidores: 532,
seguidos: 110,
cantidadDePublicaciones: 7,
posts: [],
},    
{
nombre: "Amelia",
apellido: "Wilson",
nombreDeUsuario: "ameliaaa_",
fotoDePerfil: [],
dni: 18956541,
mail: "amelitawilson@gmail.com",
contraseña: "aguaymar",
seguidores: 50.000,
seguidos: 220,
cantidadDePublicaciones: 345,
posts: [],
},    
{
nombre: "Delfina",
apellido: "Perez",
nombreDeUsuario: "delfiperezh_",
fotoDePerfil: [],
dni: 13969841,
mail: "delfinaperezh@gmail.com",
contraseña: "oceanopacifico",
seguidores: 300,
seguidos: 500,
cantidadDePublicaciones: 17,
posts: [],
},    
{
nombre: "Malena",
apellido: "Díaz",
nombreDeUsuario: "malediaz",
fotoDePerfil: [],
dni: 13997841,
mail: "malenadiaz@gmail.com",
contraseña: "1234567890",
seguidores: 400,
seguidos: 600,
cantidadDePublicaciones: 0,
posts: [],
},    
{
nombre: "Zara",
apellido: "Santurio",
nombreDeUsuario: "zarita10",
fotoDePerfil: [],
dni: 13990054,
mail: "zarasantu@gmail.com",
contraseña: "santu1234",
seguidores: 20.000,
seguidos: 600,
cantidadDePublicaciones: 270,
posts: [],
},    
{
nombre: "Mía",
apellido: "Fuleston",
nombreDeUsuario: "fulesmia",
fotoDePerfil: [],
dni: 13958816,
mail: "miafules@gmail.com",
contraseña: "abbeyroad2018",
seguidores: 300,
seguidos: 100,
cantidadDePublicaciones: 5,
posts: [],
},    
{
nombre: "Alejandro",
apellido: "Sastre",
nombreDeUsuario: "ale_sastre",
fotoDePerfil: [],
dni: 13956541,
mail: "alesastre@gmail.com",
contraseña: "playa123",
seguidores: 1.000,
seguidos: 652,
cantidadDePublicaciones: 200,
posts: [],
},    
{
nombre: "Luz",
apellido: "Sánchez",
nombreDeUsuario: "luzsanchez",
fotoDePerfil: [],
dni: 13958941,
mail: "sanchezluz@gmail.com",
contraseña: "holaquetal",
seguidores: 2000,
seguidos: 5000,
cantidadDePublicaciones: 134,
posts: [],
},    
{
nombre: "Teresita",
apellido: "Pereyra",
nombreDeUsuario: "Terepiraola",
fotoDePerfil: [],
dni: 13959901,
mail: "teresitapiraola@gmail.com",
contraseña: "digitalhouse",
seguidores: 400,
seguidos: 600,
cantidadDePublicaciones: 30,
posts: [],
},    
{
nombre: "Josefina",
apellido: "Beckerman",
nombreDeUsuario: "beckerjose",
fotoDePerfil: [],
dni: 13953471,
mail: "jbeckerman@gmail.com",
contraseña: "caballitodemar",
seguidores: 400,
seguidos: 600,
cantidadDePublicaciones: 30,
posts: [],
},    
{
nombre: "Agustín",
apellido: "Botana",
nombreDeUsuario: "botanagus",
fotoDePerfil: [],
dni: 13798941,
mail: "agustinbotana@gmail.com",
contraseña: "qwertyuiop",
seguidores: 30,
seguidos: 700,
cantidadDePublicaciones: 2,
posts: [],
},
]

module.exports = datosUsuarios;